### ISSUE TITLE
Updating config.plist causes JavaScript error

### ISSUE THREAD

**Issue by MonkaKokosowa** [mswgen/oc-updater#18]
Big Sur 11.5.2

Using 1.2.17 to update opencore from 0.6.5 to 0.9.2 fails at "Updating config.plist" state, but no errors are shown in the logs

![image](https://github.com/mswgen/oc-updater/assets/117939274/f62bf823-3ab6-4fe9-8585-c5364aaa4f9a)

Here is the config that it fails with updating if it's needed
https://pastebin.com/tNfVchvQ

**Comment by dropdb220** [comment]
The problem comes from missing NVRAM - Add - 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14.
This program is currently designed to work with a complete config.plist(ex: sample.plist).
The sample.plist of OC 0.7.5 has 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14, but in yours, it doesn't exist.
Adding the key should work.
